plugins {
    id 'java'
    id('io.qameta.allure') version '4.1.0'
}

group = 'guru.qa'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

allure {
        version.set("2.46.0")
}

dependencies {
    testImplementation (
            'com.codeborne:selenide:7.16.1',
            'org.junit.jupiter:junit-jupiter:5.11.4',
            'io.qameta.allure:allure-selenide:2.35.4'
    )

    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.withType(Test) {
    useJUnitPlatform()
//для работы с селеноидом
    systemProperties(System.getProperties())
    testLogging {
        lifecycle {
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }
}